settings:
  title: '李小团の状态页'
  url: 'https://status.lixiaotuan.cn'
  logo: logo-192x192.png
  daysInHistogram: 90
  collectResponseTimes: false

  allmonitorsOperational: '所有系统正常'
  notAllmonitorsOperational: '部分系统异常'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: '个异常'

monitors:
  - id: cloud-disk
    name: 小团云盘
    description: '团子基于白嫖来的E5接入alist搓的垃圾网盘'
    url: 'https://pan.lixiaotuan.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: front-page
    name: 团子の站
    description: '文档站兼个人博客'
    url: 'https://docs.lixiaotuan.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: chat-platform
    name: 团子のGPT
    description: '套用GPT-GOD后端接口搓的公益gpt站。注册联系QQ318504340'
    url: 'https://chat.lixiaotuan.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: private-vscode
    name: 团子VSCode
    description: '自用的网页版VSCode，非请勿入'
    url: 'https://code.lixiaotuan.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
    
  - id: sms-forward
    name: 团子短信转发
    description: '给团子看自己短信的，非请勿入'
    url: 'https://smsf.lixiaotuan.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: github-download
    name: 团子Github下载加速
    description: '本质上还是个ghproxy，慢，不建议用'
    url: 'https://dl.github.lixiaotuan.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: tg-proxy
    name: 团子TGbot镜像
    description: '镜像tg bot的接口，格式一致'
    url: 'https://tg-api.lixiaotuan.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
