name = "cf-workers-status-page"
workers_dev = true
account_id = "06273ee58b8180671b35e57f15cc64ec"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"

[env.production]
kv-namespaces = [{binding="KV_STATUS_PAGE", id="34e9344ff8ea4dcb956b806a6c0ef37a", preview_id="34e9344ff8ea4dcb956b806a6c0ef37a"}]
# zone_id="xxx"
# route="xxx"
